/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.panosmatsinopoulos.sharedmutablestateandconcurrency

import kotlinx.coroutines.*
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlin.system.measureTimeMillis

fun log(message: String) {
    println("[Thread: ${Thread.currentThread().name}] $message")
}

suspend fun massiveRun(action: suspend () -> Unit) {
    val n = 100 // number of coroutines to launch
    val k = 1_000 // times an action is repeated by each coroutine
    val time = measureTimeMillis {
        coroutineScope { // scope for coroutines
            repeat(n) {
                launch {
                    repeat(k) {
                        action()
                    }
                }
            }
        }
    }
    log("Completed ${n * k} actions in $time ms")
}

val mutex = Mutex()
var counter = 0

fun main() {
    runBlocking {
        withContext(Dispatchers.Default) {
            massiveRun {
                mutex.withLock {
                    counter++
                }
            }
        }
    }
    log("Counter now is $counter")
}
